export const TASKS_REFERENCE = [
  'Structure BA',
  'Maçonnerie et cloisons',
  'Installation EP',
  'Installation EU',
  'Installation ELC',
  'Enduit intérieur',
  'Enduit extérieur',
  'Pose faux cadre',
  'Fin GO',
  'Plâtre',
  'Carrelage',
  'Peinture',
  'Bois',
  'Aluminium',
  'Fer',
  'Électricité et plomberie',
  'Finitions',
  'Ménage',
  'Réception',
];
